### PR TITLE
Update Streamlit to 1.32.2

### PR DESCRIPTION
**Pull request by whitphx**
TODO:
* [x] Update `bootstrap.py` following https://github.com/streamlit/streamlit/pull/8113
* [x] Measure the improvement of the loading time.
* [ ] ~~Remove the lazy-loaded packages such as `altair` from `streamlit`'s requirements so they are not installed automatically at init to reduce the init time, and measure its performance improvement.~~ -> Cancel, or at least suspend this plan as https://github.com/whitphx/stlite/pull/783#issuecomment-1994003386
  * This will be a BREAKING CHANGE. Users who want to use these packages have to add them in `requirements` explicitly.

### CODE REVIEW

**Comment by whitphx** [comment]
* This PR (8e13553): https://00ddfb71.stlite-sharing.pages.dev/
* Current main (9652eb5): https://2b66a4aa.stlite-sharing.pages.dev/

**Comment by LukasMasuch** [comment]
> This might be because stlite still loads altair at initializaiton so Streamlit's lazy-loading doesn't make effects.

It might be fine to leave it in bootstrap if the `Remove the lazy-loaded packages such as altair from streamlit's requirements` aspect gets implemented. If the user adds `altair` to requirements, the user likely wants to use altair in the app. In that case, having the additional loading time is probably fine. 
Do you know how long it takes if `altair` is not installed?

**Comment by whitphx** [comment]
Thanks, it makes sense.
However I fixed `_fix_altair` before seeing your comment and it lazily patches `altair` when it's imported. I think this approach has some benefits such as
* The loading time before the first view should be shortened as the loading time of `altair` is included in the first usage time of `st.altair_chart`.
* This patch works even when `altair` is installed and imported after the initial load, which is kind of an edge-case.

**Comment by whitphx** [comment]
Removing the matplotlib patch resulted in reducing the init loading time from ~5.2s to ~4.9s.
https://docs.google.com/spreadsheets/d/1z_y0G_KldMg6JrrJ82cVU8e5NRTIo51S9ExEQa5IdkM/edit?hl=ja&pli=1#gid=0

**Comment by whitphx** [comment]
3f6b1ba introduced the lazy `altair` patching.
It reduced the booting-up time from ~4.9s to ~0.15s!

**Comment by whitphx** [comment]
After e2f668e which removed the `click` dependency,
there are 4 Streamlit's dependencies that can be omitted from the depds list.
* `altair`: Used by `st.altair_chart` and all the built-in charts, ~6% usage.
* `pillow`: Used by `st.image` and `st.pyplot`, and lazily loaded.  ~30% usage.
* `tenacity`: Used by `st.connection` and lazily loaded. ~1% usage.
* `toml`: Used by config and secret toml parser.

We should consider to remove them or not.
The benefits are reducing the initial loading payload size and loading time.
The downside is breaking the interoperability to Streamlit and inconvenience for the users who want to use these libraries where they have to declare such requirements explicitly.

**Comment by whitphx** [comment]
## Measure the performance improvements when removing these packages
1. Set the performance API in `worker.ts` around the package installation.
```diff
--- a/packages/kernel/src/worker.ts
+++ b/packages/kernel/src/worker.ts
@@ -172,6 +172,7 @@ async function loadPyodideAndPackages() {
   postProgressMessage("Installing packages.");
   await pyodide.loadPackage("micropip");
   const micropip = pyodide.pyimport("micropip");
+  performance.mark('start:install');
   if (wheels) {
     console.debug(
       "Installing the wheels:",
@@ -194,6 +195,8 @@ async function loadPyodideAndPackages() {
     await micropip.install.callKwargs(requirements, { keep_going: true });
     console.debug("Installed the requirements");
   }
+  performance.mark('end:install');
+  console.log("PERF:", performance.measure('install', 'start:install', 'end:install'));

   // The following code is necessary to avoid errors like  `NameError: name '_imp' is not defined`
   // at importing installed packages.
```
2. Build the wheel file for each setting (modifying `streamlit/lib/setup.py`)
3. Start the `sharing` dev server (`cd packages/sharing & yarn start`)
4. Open the page and log the performance in each case.


### Baseline (e2f668e)
pyodide.asm.js:9 Loading typing-extensions, cachetools, protobuf, numpy, pillow, fastparquet, cramjam, pandas, python-dateutil, six, pytz, fsspec, pyodide-http, jinja2, markupsafe, toolz, jsonschema, attrs, pyrsistent
92.0MB
* 1341.2000000001863
* 1339.2999999998137
* 1343.8999999994412
* 1431.1000000005588
* 1387.2000000001863
* 1366.7000000001863

### Remove all:
86.5MB
pyodide.asm.js:9 Loading protobuf, pandas, numpy, python-dateutil, six, pytz, typing-extensions, fastparquet, cramjam, fsspec, cachetools, pyodide-http
* 1029.6000000005588
* 1004.7000000001863
* 1030.2999999998137
* 1053.3999999994412
* 1064.2999999998137
* 1197.5999999996275

### Remove only `altiar`:
pyodide.asm.js:9 Loading pillow, cachetools, numpy, protobuf, typing-extensions, fastparquet, cramjam, pandas, python-dateutil, six, pytz, fsspec, pyodide-http
89.6MB
* 1134.7999999998137
* 1143
* 1205.4000000003725
* 1147.0999999996275
* 1148.7999999998137
* 1159.8999999994412

### Remove only `pillow`:
pyodide.asm.js:9 Loading pandas, numpy, python-dateutil, six, pytz, typing-extensions, pyodide-http, cachetools, fastparquet, cramjam, fsspec, protobuf, jsonschema, attrs, pyrsistent, jinja2, markupsafe, toolz
89.0MB
* 1252.7999999998137
* 1318
* 1312.1000000005588
* 1334
* 1329
* 1307.1000000005588

### Remove only `tenacity`:
pyodide.asm.js:9 Loading protobuf, pandas, numpy, python-dateutil, six, pytz, pillow, typing-extensions, fastparquet, cramjam, fsspec, pyodide-http, cachetools, jsonschema, attrs, pyrsistent, jinja2, markupsafe, toolz
91.9MB
* 1324.5
* 1319.5
* 1312.2999999998137
* 1369.5
* 1445.9000000003725
* 1389.5

### Remove only `toml`:
pyodide.asm.js:9 packaging already loaded from default channel
18:45:43.076 pyodide.asm.js:9 Loading typing-extensions, fastparquet, cramjam, numpy, pandas, python-dateutil, six, pytz, fsspec, protobuf, pillow, pyodide-http, cachetools, jsonschema, attrs, pyrsistent, toolz, jinja2, markupsafe
92.0MB
* 1343.3999999994412
* 1390.3999999994412
* 1390.3999999994412
* 1410.6000000005588
* 1482.7000000001863
* 1359.699999999255

**Comment by LukasMasuch** [comment]
Awesome analysis :) 

Do you know where `python-dateutil` is coming from? It's one of the dependencies that Streamlit removed in the last version. 

`altair`, `pillow`, and `tenacity` might be good candidates to remove once we find a good way for a lazy install feature.

**Review by LukasMasuch — APPROVED** [review]
LGTM 👍  But 1.32.1 still has an issue causing significant CPU load. We will likely roll out the 1.32.2 patch fixing this in a couple of hours.

**Comment by whitphx** [comment]
@LukasMasuch Thanks

> Do you know where python-dateutil is coming from?

Looks like it's a `pandas`' dependency.
Even with normal Streamlit, `python-dateutil` is installed along with `pandas`.

> altair, pillow, and tenacity might be good candidates to remove once we find a good way for a lazy install feature.

Indeed!

> We will likely roll out the 1.32.2 patch fixing this in a couple of hours.

Thanks! Will wait for and merge it.

**Comment by whitphx** [comment]
I came up with this idea of lazy-install -> https://github.com/whitphx/streamlit/pull/9

**Pull request merged**
